language: node_js
node_js:
  - 'stable'
before_script:
  - npm prune
jobs:
  include:
    - stage: test
      script:
        - echo "Linting ..." && npm run lint
        - echo "Create Documentation ..." && npm run docs
after-success:
  - echo "Semantic Release Deployment .."
  - npm run semantic-release
branches:
  only:
    - master
notifications:
  email: false
